#!/usr/bin/env python3
"""Generate a Strata-importable order (.sbx) from a Sample Buy workbook --
including one a buyer has hand-edited (changed day quantities, rates, or
added/removed rows) after the initial build_sample_buy.py run.

Usage:
    python3 build_strata_order.py sample_buy.xlsx --market-name "Milwaukee, WI" \
        --flight-start 2026-07-06 --flight-end 2026-09-27 -o output/sample_buy.sbx
"""

import argparse

from broadcast_buy.pipeline import build_strata_order_from_workbook


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("workbook", help="Sample Buy .xlsx file (as generated by build_sample_buy.py, edited or not)")
    parser.add_argument("--market-name", required=True)
    parser.add_argument("--flight-start", required=True, help="YYYY-MM-DD")
    parser.add_argument("--flight-end", required=True, help="YYYY-MM-DD")
    parser.add_argument("--target-demo-group", default="Adults")
    parser.add_argument("--target-demo-age", type=int, default=35)
    parser.add_argument("--campaign-name", default=None)
    parser.add_argument("-o", "--output", default=None, help="Defaults to <workbook>.sbx")
    args = parser.parse_args()

    output = args.output or (args.workbook.rsplit(".", 1)[0] + ".sbx")
    log_lines = build_strata_order_from_workbook(
        args.workbook,
        output,
        market_name=args.market_name,
        flight_start=args.flight_start,
        flight_end=args.flight_end,
        target_demo_group=args.target_demo_group,
        target_demo_age=args.target_demo_age,
        campaign_name=args.campaign_name,
    )
    for line in log_lines:
        print(line)
    print(f"\nWrote {output}")


if __name__ == "__main__":
    main()
